name: Daily Oracle DBA Job Alert

on:
  schedule:
    - cron: "0 8 * * *" # Runs at 8:00 AM UTC daily
  workflow_dispatch: # Allows manual trigger

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Oracle DBA Job Alert script
        run: python daily_oracle_dba_job_alert.py
